<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 ./static/model/scene.gltf
Author: TadenStar (https://sketchfab.com/tadenstar)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hummingbird-flying-4e6d591f6e50493aa5e31355084fc4e8
Title: Hummingbird | Flying
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/static/model/scene.gltf')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.05}>
        <T.Group name="root">
          <T.Group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
            <T.Group name="05_Colibri_Bird001_13">
              <T.Group name="GLTF_created_0">
                <T is={gltf.nodes.GLTF_created_0_rootJoint} />
                <T.Group name="05_Colibri001_12" />
                <T.SkinnedMesh
                  name="Object_7"
                  geometry={gltf.nodes.Object_7.geometry}
                  material={gltf.materials['05_Colibri_Bird_Body']}
                  skeleton={gltf.nodes.Object_7.skeleton}
                />
              </T.Group>
            </T.Group>
            <T.Group name="05_Colibri_Bird002_81">
              <T.Group name="BigBranch_Root001_61" position={[-7.04, -7.7, -0.49]} rotation={[-0.94, -0.83, -1.41]}>
                <T.Group name="BigBranch_01001_55" position={[0, 3.48, 0]} rotation={[-0.37, -0.07, -0.24]}>
                  <T.Group name="BigBranch_02001_31" position={[0, 1.62, 0]} rotation={[0, -0.03, -0.04]}>
                    <T.Group name="BigBranch_03001_28" position={[0, 1.25, 0]} rotation={[-0.28, -0.01, -0.07]}>
                      <T.Group name="BigBranch_04001_25" position={[0, 1.79, 0]} rotation={[-0.16, -0.02, 0.26]}>
                        <T.Group name="BigBranch_05001_24" position={[0, 2.3, 0]} rotation={[-0.32, 0.03, -0.08]}>
                          <T.Group name="BigBranch_06001_19" position={[0, 1.5, 0]} rotation={[0.98, 0.2, 0.1]}>
                            <T.Group name="BigBranch_07001_18" position={[0, 1.43, 0]} rotation={[-0.31, -0.01, -0.03]}>
                              <T.Group name="BigBranch_08001_17" position={[0, 1.14, 0]} rotation={[0.65, 0.2, 0.37]}>
                                <T.Group
                                  name="BigBranch_09001_16"
                                  position={[0, 1.23, 0]}
                                  rotation={[0.42, 0.08, 0.06]}
                                >
                                  <T.Group
                                    name="BigBranch_10001_15"
                                    position={[0, 1.15, 0]}
                                    rotation={[0.68, 0.23, 0.29]}
                                  >
                                    <T.Group
                                      name="BigBranch_Flower_01001_14"
                                      position={[0, 0.79, 0]}
                                      rotation={[0.13, 0.03, 0.32]}
                                    />
                                  </T.Group>
                                </T.Group>
                              </T.Group>
                            </T.Group>
                          </T.Group>
                          <T.Group
                            name="BigBranch_Leaf_11001_20"
                            position={[0, 1.5, 0]}
                            rotation={[1.39, -0.35, 0.09]}
                          />
                          <T.Group
                            name="BigBranch_Leaf_12001_21"
                            position={[0, 1.5, 0]}
                            rotation={[2.17, 0.86, 0.76]}
                          />
                          <T.Group
                            name="BigBranch_Leaf_13001_23"
                            position={[0, 1.5, 0]}
                            rotation={[0.59, -0.03, -0.06]}
                          >
                            <T.Group
                              name="BigBranchLeaf_13_01001_22"
                              position={[0, 1.43, 0]}
                              rotation={[-0.37, -0.08, 0.04]}
                            />
                          </T.Group>
                        </T.Group>
                      </T.Group>
                      <T.Group name="BigBranch_Leaf_08001_26" position={[0, 1.79, 0]} rotation={[1.24, 0.82, 0.13]} />
                      <T.Group name="BigBranch_Leaf_09001_27" position={[0, 1.79, 0]} rotation={[-1.53, -0.18, 0.07]} />
                    </T.Group>
                    <T.Group name="BigBranch_Leaf_06001_29" position={[0, 1.25, 0]} rotation={[1.01, 0.26, 0.47]} />
                    <T.Group name="BigBranch_Leaf_07001_30" position={[0, 1.25, 0]} rotation={[-1.12, 0.14, -0.35]} />
                  </T.Group>
                  <T.Group name="BigBranch_02_01001_54" position={[0, 1.62, 0]} rotation={[-0.96, -0.07, -0.22]}>
                    <T.Group name="BigBranch_02_02001_52" position={[0, 1.25, 0]} rotation={[0.53, 0.09, 0.02]}>
                      <T.Group name="BigBranch_02_03_01001_41" position={[0, 0.61, 0]} rotation={[-0.8, 0.4, -0.19]}>
                        <T.Group name="BigBranch_02_03_02001_40" position={[0, 0.95, 0]} rotation={[0.06, -0.01, 0.07]}>
                          <T.Group
                            name="BigBranch_02_03_Flower_03001_39"
                            position={[0, 1.13, 0]}
                            rotation={[0.15, -0.01, -0.37]}
                          >
                            <T.Group
                              name="BigBranch_02_03_Flower_03_Petal_01001_32"
                              position={[0, 0.76, 0]}
                              rotation={[0.88, 0.33, 1.37]}
                            />
                            <T.Group
                              name="BigBranch_02_03_Flower_03_Petal_02001_33"
                              position={[0, 0.76, 0]}
                              rotation={[-0.14, 0.08, -0.44]}
                            />
                            <T.Group
                              name="BigBranch_02_03_Flower_03_Petal_03001_34"
                              position={[0, 0.76, 0]}
                              rotation={[-1.53, -0.33, 0.72]}
                            />
                            <T.Group
                              name="BigBranch_02_03_Flower_03_Petal_04001_35"
                              position={[0, 0.76, 0]}
                              rotation={[0.06, 0.15, 0.87]}
                            />
                            <T.Group
                              name="BigBranch_02_03_Flower_03_Petal_05001_36"
                              position={[0, 0.76, 0]}
                              rotation={[0.04, 0.12, 0.31]}
                            />
                            <T.Group
                              name="BigBranch_02_03_Flower_03_Petal_06001_37"
                              position={[0, 0.76, 0]}
                              rotation={[-0.59, 0, 0]}
                            />
                            <T.Group
                              name="BigBranch_02_03_Flower_03_Petal_07001_38"
                              position={[0, 0.76, 0]}
                              rotation={[-0.85, -0.35, 0.44]}
                            />
                          </T.Group>
                        </T.Group>
                      </T.Group>
                      <T.Group name="BigBranch_02_04_01001_51" position={[0, 0.61, 0]} rotation={[0.38, 0.08, 0.1]}>
                        <T.Group
                          name="BigBranch_02_04_02001_50"
                          position={[0, 1.06, 0]}
                          rotation={[-0.44, -0.02, -0.13]}
                        >
                          <T.Group
                            name="BigBranch_02_04_Flower_04001_49"
                            position={[0, 1.13, 0]}
                            rotation={[-0.48, 0.01, -0.25]}
                          >
                            <T.Group
                              name="BigBranch_02_04_Flower_04_Petal_01001_42"
                              position={[0, 1.07, 0]}
                              rotation={[0, 0.09, -0.08]}
                              scale={[0.2, 0, 0]}
                            />
                            <T.Group
                              name="BigBranch_02_04_Flower_04_Petal_02001_43"
                              position={[0, 1.07, 0]}
                              rotation={[-0.94, -0.01, -0.21]}
                            />
                            <T.Group
                              name="BigBranch_02_04_Flower_04_Petal_03001_44"
                              position={[0, 1.07, 0]}
                              rotation={[0.49, 0.44, 1.42]}
                            />
                            <T.Group
                              name="BigBranch_02_04_Flower_04_Petal_04001_45"
                              position={[0, 1.07, 0]}
                              rotation={[-0.61, -0.19, 0.68]}
                            />
                            <T.Group
                              name="BigBranch_02_04_Flower_04_Petal_05001_46"
                              position={[0, 1.07, 0]}
                              rotation={[0.72, -0.06, -0.11]}
                            />
                            <T.Group
                              name="BigBranch_02_04_Flower_04_Petal_06001_47"
                              position={[0, 1.07, 0]}
                              rotation={[0.07, 0.46, 0.7]}
                            />
                            <T.Group
                              name="BigBranch_02_04_Flower_04_Petal_07001_48"
                              position={[0, 1.07, 0]}
                              rotation={[-0.12, -0.03, -0.37]}
                            />
                          </T.Group>
                        </T.Group>
                      </T.Group>
                    </T.Group>
                    <T.Group
                      name="BigBranch_02_02_Flower_02001_53"
                      position={[0, 1.25, 0]}
                      rotation={[-1.24, 0.11, 0.2]}
                    />
                  </T.Group>
                </T.Group>
                <T.Group name="BigBranch_Leaf_05001_56" position={[0, 3.48, 0]} rotation={[-0.06, 0.77, 1.59]} />
                <T.Group name="BigBranch_Leaf_01001_57" position={[0, 3.48, 0]} rotation={[2.51, -0.72, -0.25]} />
                <T.Group name="BigBranch_Leaf_02001_58" position={[0, 3.48, 0]} rotation={[-2.19, -0.26, -0.08]} />
                <T.Group name="BigBranch_Leaf_03001_59" position={[0, 3.48, 0]} rotation={[0.14, 0.01, -0.4]} />
                <T.Group name="BigBranch_Leaf_04001_60" position={[0, 3.48, 0]} rotation={[1.3, 0.04, 0.06]} />
              </T.Group>
              <T.Group
                name="SmallBranch_Petal_01_Fix_62"
                position={[-4.3, 5.22, 0.4]}
                rotation={[-0.31, -0.78, -2.91]}
              />
              <T.Group
                name="SmallBranch_Petal_02_01_Fix_64"
                position={[-4.3, 5.22, 0.4]}
                rotation={[-2.99, 0.23, -0.22]}
              >
                <T.Group name="SmallBranch_Petal_02_02_63" position={[0, 2.24, 0]} rotation={[-0.44, 0.01, -0.13]} />
              </T.Group>
              <T.Group
                name="SmallBranch_Petal_03_01_FIx_66"
                position={[-4.3, 5.22, 0.4]}
                rotation={[-2.66, -0.56, 0.41]}
              >
                <T.Group name="SmallBranch_Petal_03_02_65" position={[0, 2.62, 0]} rotation={[-0.68, -0.13, -0.04]} />
              </T.Group>
              <T.Group name="SmallBranch_Petal_04_Fix_67" position={[-4.3, 5.22, 0.4]} rotation={[-1.85, -0.3, 0.88]} />
              <T.Group name="SmallBranch_Petal_05_Fix_68" position={[-4.3, 5.22, 0.4]} rotation={[-1.6, 0.04, 1.12]} />
              <T.Group name="SmallBranch_Petal_06_Fix_69" position={[-4.3, 5.22, 0.4]} rotation={[3.05, 0.4, 3.07]} />
              <T.Group
                name="SmallBranch_Petal_07_01_Fix_71"
                position={[-4.3, 5.22, 0.4]}
                rotation={[-1.78, 0.69, -1.42]}
              >
                <T.Group name="SmallBranch_Petal_07_02_70" position={[0, 2.31, 0]} rotation={[-0.11, 0.04, -0.52]} />
              </T.Group>
              <T.Group name="SmallBranch_01_80" position={[-4.3, 5.22, 0.4]} rotation={[-1.58, -0.32, -1.58]}>
                <T.Group name="SmallBranch_Petal_08_72" position={[0, 1.03, 0]} rotation={[0.7, -0.04, -0.12]} />
                <T.Group name="SmallBranch_02_76" position={[0, 1.03, 0]} rotation={[0.11, 0, 0.31]}>
                  <T.Group name="SmallBranch_02_01_75" position={[0, 1.3, 0]} rotation={[0.02, 0, -0.23]}>
                    <T.Group name="SmallBranch_02_02_74" position={[0, 1.97, 0]} rotation={[-0.98, 0.35, -0.39]}>
                      <T.Group
                        name="SmallBranch_02_Flower_01_73"
                        position={[0, 2.25, 0]}
                        rotation={[-0.03, 0.3, -0.28]}
                      />
                    </T.Group>
                  </T.Group>
                </T.Group>
                <T.Group name="SmallBranch_03_79" position={[0, 1.03, 0]} rotation={[-0.03, -0.21, 0.26]}>
                  <T.Group name="SmallBranch_03_01_78" position={[0, 2.28, 0]} rotation={[-0.52, 0.01, 0.14]}>
                    <T.Group
                      name="SmallBranch_03_Flower_02_77"
                      position={[0, 2.04, 0]}
                      rotation={[-0.73, -0.2, -0.12]}
                    />
                  </T.Group>
                </T.Group>
              </T.Group>
            </T.Group>
            <T.Group name="05_Colibri_Bird003_149">
              <T.Group name="BigBranch_Root001_129" position={[-7.04, -7.7, -0.49]} rotation={[-0.94, -0.83, -1.41]}>
                <T.Group name="BigBranch_01001_123" position={[0, 3.48, 0]} rotation={[-0.37, -0.07, -0.24]}>
                  <T.Group name="BigBranch_02001_99" position={[0, 1.62, 0]} rotation={[0, -0.03, -0.04]}>
                    <T.Group name="BigBranch_03001_96" position={[0, 1.25, 0]} rotation={[-0.28, -0.01, -0.07]}>
                      <T.Group name="BigBranch_04001_93" position={[0, 1.79, 0]} rotation={[-0.16, -0.02, 0.26]}>
                        <T.Group name="BigBranch_05001_92" position={[0, 2.3, 0]} rotation={[-0.32, 0.03, -0.08]}>
                          <T.Group name="BigBranch_06001_87" position={[0, 1.5, 0]} rotation={[0.98, 0.2, 0.1]}>
                            <T.Group name="BigBranch_07001_86" position={[0, 1.43, 0]} rotation={[-0.31, -0.01, -0.03]}>
                              <T.Group name="BigBranch_08001_85" position={[0, 1.14, 0]} rotation={[0.65, 0.2, 0.37]}>
                                <T.Group
                                  name="BigBranch_09001_84"
                                  position={[0, 1.23, 0]}
                                  rotation={[0.42, 0.08, 0.06]}
                                >
                                  <T.Group
                                    name="BigBranch_10001_83"
                                    position={[0, 1.15, 0]}
                                    rotation={[0.68, 0.23, 0.29]}
                                  >
                                    <T.Group
                                      name="BigBranch_Flower_01001_82"
                                      position={[0, 0.79, 0]}
                                      rotation={[0.13, 0.03, 0.32]}
                                    />
                                  </T.Group>
                                </T.Group>
                              </T.Group>
                            </T.Group>
                          </T.Group>
                          <T.Group
                            name="BigBranch_Leaf_11001_88"
                            position={[0, 1.5, 0]}
                            rotation={[1.39, -0.35, 0.09]}
                          />
                          <T.Group
                            name="BigBranch_Leaf_12001_89"
                            position={[0, 1.5, 0]}
                            rotation={[2.17, 0.86, 0.76]}
                          />
                          <T.Group
                            name="BigBranch_Leaf_13001_91"
                            position={[0, 1.5, 0]}
                            rotation={[0.59, -0.03, -0.06]}
                          >
                            <T.Group
                              name="BigBranchLeaf_13_01001_90"
                              position={[0, 1.43, 0]}
                              rotation={[-0.37, -0.08, 0.04]}
                            />
                          </T.Group>
                        </T.Group>
                      </T.Group>
                      <T.Group name="BigBranch_Leaf_08001_94" position={[0, 1.79, 0]} rotation={[1.24, 0.82, 0.13]} />
                      <T.Group name="BigBranch_Leaf_09001_95" position={[0, 1.79, 0]} rotation={[-1.53, -0.18, 0.07]} />
                    </T.Group>
                    <T.Group name="BigBranch_Leaf_06001_97" position={[0, 1.25, 0]} rotation={[1.01, 0.26, 0.47]} />
                    <T.Group name="BigBranch_Leaf_07001_98" position={[0, 1.25, 0]} rotation={[-1.12, 0.14, -0.35]} />
                  </T.Group>
                  <T.Group name="BigBranch_02_01001_122" position={[0, 1.62, 0]} rotation={[-0.96, -0.07, -0.22]}>
                    <T.Group name="BigBranch_02_02001_120" position={[0, 1.25, 0]} rotation={[0.53, 0.09, 0.02]}>
                      <T.Group name="BigBranch_02_03_01001_109" position={[0, 0.61, 0]} rotation={[-0.8, 0.4, -0.19]}>
                        <T.Group
                          name="BigBranch_02_03_02001_108"
                          position={[0, 0.95, 0]}
                          rotation={[0.06, -0.01, 0.07]}
                        >
                          <T.Group
                            name="BigBranch_02_03_Flower_03001_107"
                            position={[0, 1.13, 0]}
                            rotation={[0.15, -0.01, -0.37]}
                          >
                            <T.Group
                              name="BigBranch_02_03_Flower_03_Petal_01001_100"
                              position={[0, 0.76, 0]}
                              rotation={[0.88, 0.33, 1.37]}
                            />
                            <T.Group
                              name="BigBranch_02_03_Flower_03_Petal_02001_101"
                              position={[0, 0.76, 0]}
                              rotation={[-0.14, 0.08, -0.44]}
                            />
                            <T.Group
                              name="BigBranch_02_03_Flower_03_Petal_03001_102"
                              position={[0, 0.76, 0]}
                              rotation={[-1.53, -0.33, 0.72]}
                            />
                            <T.Group
                              name="BigBranch_02_03_Flower_03_Petal_04001_103"
                              position={[0, 0.76, 0]}
                              rotation={[0.06, 0.15, 0.87]}
                            />
                            <T.Group
                              name="BigBranch_02_03_Flower_03_Petal_05001_104"
                              position={[0, 0.76, 0]}
                              rotation={[0.04, 0.12, 0.31]}
                            />
                            <T.Group
                              name="BigBranch_02_03_Flower_03_Petal_06001_105"
                              position={[0, 0.76, 0]}
                              rotation={[-0.59, 0, 0]}
                            />
                            <T.Group
                              name="BigBranch_02_03_Flower_03_Petal_07001_106"
                              position={[0, 0.76, 0]}
                              rotation={[-0.85, -0.35, 0.44]}
                            />
                          </T.Group>
                        </T.Group>
                      </T.Group>
                      <T.Group name="BigBranch_02_04_01001_119" position={[0, 0.61, 0]} rotation={[0.38, 0.08, 0.1]}>
                        <T.Group
                          name="BigBranch_02_04_02001_118"
                          position={[0, 1.06, 0]}
                          rotation={[-0.44, -0.02, -0.13]}
                        >
                          <T.Group
                            name="BigBranch_02_04_Flower_04001_117"
                            position={[0, 1.13, 0]}
                            rotation={[-0.48, 0.01, -0.25]}
                          >
                            <T.Group
                              name="BigBranch_02_04_Flower_04_Petal_01001_110"
                              position={[0, 1.07, 0]}
                              rotation={[0, 0.09, -0.08]}
                              scale={[0.2, 0, 0]}
                            />
                            <T.Group
                              name="BigBranch_02_04_Flower_04_Petal_02001_111"
                              position={[0, 1.07, 0]}
                              rotation={[-0.94, -0.01, -0.21]}
                            />
                            <T.Group
                              name="BigBranch_02_04_Flower_04_Petal_03001_112"
                              position={[0, 1.07, 0]}
                              rotation={[0.49, 0.44, 1.42]}
                            />
                            <T.Group
                              name="BigBranch_02_04_Flower_04_Petal_04001_113"
                              position={[0, 1.07, 0]}
                              rotation={[-0.61, -0.19, 0.68]}
                            />
                            <T.Group
                              name="BigBranch_02_04_Flower_04_Petal_05001_114"
                              position={[0, 1.07, 0]}
                              rotation={[0.72, -0.06, -0.11]}
                            />
                            <T.Group
                              name="BigBranch_02_04_Flower_04_Petal_06001_115"
                              position={[0, 1.07, 0]}
                              rotation={[0.07, 0.46, 0.7]}
                            />
                            <T.Group
                              name="BigBranch_02_04_Flower_04_Petal_07001_116"
                              position={[0, 1.07, 0]}
                              rotation={[-0.12, -0.03, -0.37]}
                            />
                          </T.Group>
                        </T.Group>
                      </T.Group>
                    </T.Group>
                    <T.Group
                      name="BigBranch_02_02_Flower_02001_121"
                      position={[0, 1.25, 0]}
                      rotation={[-1.24, 0.11, 0.2]}
                    />
                  </T.Group>
                </T.Group>
                <T.Group name="BigBranch_Leaf_05001_124" position={[0, 3.48, 0]} rotation={[-0.06, 0.77, 1.59]} />
                <T.Group name="BigBranch_Leaf_01001_125" position={[0, 3.48, 0]} rotation={[2.51, -0.72, -0.25]} />
                <T.Group name="BigBranch_Leaf_02001_126" position={[0, 3.48, 0]} rotation={[-2.19, -0.26, -0.08]} />
                <T.Group name="BigBranch_Leaf_03001_127" position={[0, 3.48, 0]} rotation={[0.14, 0.01, -0.4]} />
                <T.Group name="BigBranch_Leaf_04001_128" position={[0, 3.48, 0]} rotation={[1.3, 0.04, 0.06]} />
              </T.Group>
              <T.Group
                name="SmallBranch_Petal_01_Fix_130"
                position={[-4.3, 5.22, 0.4]}
                rotation={[-0.31, -0.78, -2.91]}
              />
              <T.Group
                name="SmallBranch_Petal_02_01_Fix_132"
                position={[-4.3, 5.22, 0.4]}
                rotation={[-2.99, 0.23, -0.22]}
              >
                <T.Group name="SmallBranch_Petal_02_02_131" position={[0, 2.24, 0]} rotation={[-0.44, 0.01, -0.13]} />
              </T.Group>
              <T.Group
                name="SmallBranch_Petal_03_01_FIx_134"
                position={[-4.3, 5.22, 0.4]}
                rotation={[-2.66, -0.56, 0.41]}
              >
                <T.Group name="SmallBranch_Petal_03_02_133" position={[0, 2.62, 0]} rotation={[-0.68, -0.13, -0.04]} />
              </T.Group>
              <T.Group
                name="SmallBranch_Petal_04_Fix_135"
                position={[-4.3, 5.22, 0.4]}
                rotation={[-1.85, -0.3, 0.88]}
              />
              <T.Group name="SmallBranch_Petal_05_Fix_136" position={[-4.3, 5.22, 0.4]} rotation={[-1.6, 0.04, 1.12]} />
              <T.Group name="SmallBranch_Petal_06_Fix_137" position={[-4.3, 5.22, 0.4]} rotation={[3.05, 0.4, 3.07]} />
              <T.Group
                name="SmallBranch_Petal_07_01_Fix_139"
                position={[-4.3, 5.22, 0.4]}
                rotation={[-1.78, 0.69, -1.42]}
              >
                <T.Group name="SmallBranch_Petal_07_02_138" position={[0, 2.31, 0]} rotation={[-0.11, 0.04, -0.52]} />
              </T.Group>
              <T.Group name="SmallBranch_01_148" position={[-4.3, 5.22, 0.4]} rotation={[-1.58, -0.32, -1.58]}>
                <T.Group name="SmallBranch_Petal_08_140" position={[0, 1.03, 0]} rotation={[0.7, -0.04, -0.12]} />
                <T.Group name="SmallBranch_02_144" position={[0, 1.03, 0]} rotation={[0.11, 0, 0.31]}>
                  <T.Group name="SmallBranch_02_01_143" position={[0, 1.3, 0]} rotation={[0.02, 0, -0.23]}>
                    <T.Group name="SmallBranch_02_02_142" position={[0, 1.97, 0]} rotation={[-0.98, 0.35, -0.39]}>
                      <T.Group
                        name="SmallBranch_02_Flower_01_141"
                        position={[0, 2.25, 0]}
                        rotation={[-0.03, 0.3, -0.28]}
                      />
                    </T.Group>
                  </T.Group>
                </T.Group>
                <T.Group name="SmallBranch_03_147" position={[0, 1.03, 0]} rotation={[-0.03, -0.21, 0.26]}>
                  <T.Group name="SmallBranch_03_01_146" position={[0, 2.28, 0]} rotation={[-0.52, 0.01, 0.14]}>
                    <T.Group
                      name="SmallBranch_03_Flower_02_145"
                      position={[0, 2.04, 0]}
                      rotation={[-0.73, -0.2, -0.12]}
                    />
                  </T.Group>
                </T.Group>
              </T.Group>
            </T.Group>
            <T.Group
              name="05_Colibri_SmallBrach_174"
              position={[-5.76, 7.36, 0.4]}
              rotation={[1.34, 0.13, 0.15]}
              scale={1.2}
            >
              <T.Group name="SmallBranch_Petal_07_151" rotation={[0, 0, -Math.PI]} scale={0}>
                <T.Group name="SmallBranch_Petal_07_01_150" rotation={[0, 0, -Math.PI]} scale={0} />
              </T.Group>
              <T.Group name="SmallBranch_Petal_06_154" rotation={[0, 0, -Math.PI]} scale={0}>
                <T.Group name="SmallBranch_Petal_06_01_153" rotation={[0, 0, -Math.PI]} scale={0}>
                  <T.Group name="SmallBranch_Petal_06_02_152" rotation={[0, 0, -Math.PI]} scale={0} />
                </T.Group>
              </T.Group>
              <T.Group name="SmallBranch_Petal_05_157" rotation={[0, 0, -Math.PI]} scale={0}>
                <T.Group name="SmallBranch_Petal_05_01_156" rotation={[0, 0, -Math.PI]} scale={0}>
                  <T.Group name="SmallBranch_Petal_05_02_155" rotation={[0, 0, -Math.PI]} scale={0} />
                </T.Group>
              </T.Group>
              <T.Group name="SmallBranch_Petal_03_159" rotation={[0, 0, -Math.PI]} scale={0}>
                <T.Group name="SmallBranch_Petal_03_01_158" rotation={[0, 0, -Math.PI]} scale={0} />
              </T.Group>
              <T.Group name="SmallBranch_Petal_04_161" rotation={[0, 0, -Math.PI]} scale={0}>
                <T.Group name="SmallBranch_Petal_04_01_160" rotation={[0, 0, -Math.PI]} scale={0} />
              </T.Group>
              <T.Group name="SmallBranch_Petal_02_163" rotation={[0, 0, -Math.PI]} scale={0}>
                <T.Group name="SmallBranch_Petal_02_01_162" rotation={[0, 0, -Math.PI]} scale={0} />
              </T.Group>
              <T.Group name="SmallBranch_Petal_01_165" rotation={[0, 0, -Math.PI]} scale={0}>
                <T.Group name="SmallBranch_Petal_01_01_164" rotation={[0, 0, -Math.PI]} scale={0} />
              </T.Group>
              <T.Group name="SmallBranch_Leaf_to_Branch_173" rotation={[0, 0, -Math.PI]} scale={0}>
                <T.Group name="SmallBranch_Branch_02_168" rotation={[0, 0, -Math.PI]} scale={0}>
                  <T.Group name="SmallBranch_Branch_02_01_167" rotation={[0, 0, -Math.PI]} scale={0}>
                    <T.Group name="SmallBranch_Branch_02_Flower_02_166" rotation={[0, 0, -Math.PI]} scale={0} />
                  </T.Group>
                </T.Group>
                <T.Group name="SmallBranch_Branch_01_172" rotation={[0, 0, -Math.PI]} scale={0}>
                  <T.Group name="SmallBranch_Branch_01_01_171" rotation={[0, 0, -Math.PI]} scale={0}>
                    <T.Group name="SmallBranch_Branch_01_02_170" rotation={[0, 0, -Math.PI]} scale={0}>
                      <T.Group name="SmallBranch_Branch_01_Flower_01_169" rotation={[0, 0, -Math.PI]} scale={0} />
                    </T.Group>
                  </T.Group>
                </T.Group>
              </T.Group>
            </T.Group>
            <T.Group name="05_Colibri_BigBrach_215" position={[-7.7, -8.39, -1.3]} rotation={[1.85, 0.17, 0.13]}>
              <T.Group name="BigBranch_01_214" rotation={[0, 0, -Math.PI]} scale={0}>
                <T.Group name="BigBranch_02_210" rotation={[0, 0, -Math.PI]} scale={0}>
                  <T.Group name="BigBranch_03_208" rotation={[0, 0, -Math.PI]} scale={0}>
                    <T.Group name="BigBranch_04_190" rotation={[0, 0, -Math.PI]} scale={0}>
                      <T.Group name="BigBranch_05_187" rotation={[0, 0, -Math.PI]} scale={0}>
                        <T.Group name="BigBranch_06_186" rotation={[0, 0, -Math.PI]} scale={0}>
                          <T.Group name="BigBranch_07_185" rotation={[0, 0, -Math.PI]} scale={0}>
                            <T.Group name="BigBranch_08_180" rotation={[0, 0, -Math.PI]} scale={0}>
                              <T.Group name="BigBranch_09_179" rotation={[0, 0, -Math.PI]} scale={0}>
                                <T.Group name="BigBranch_10_178" rotation={[0, 0, -Math.PI]} scale={0}>
                                  <T.Group name="BigBranch_11_177" rotation={[0, 0, -Math.PI]} scale={0}>
                                    <T.Group name="BigBranch_12_176" rotation={[0, 0, -Math.PI]} scale={0}>
                                      <T.Group name="BigBranch_Flower_04_175" rotation={[0, 0, -Math.PI]} scale={0} />
                                    </T.Group>
                                  </T.Group>
                                </T.Group>
                              </T.Group>
                            </T.Group>
                            <T.Group name="BigBranch_Leaf_07_181" rotation={[0, 0, -Math.PI]} scale={0} />
                            <T.Group name="BigBranch_Leaf_08_01_183" rotation={[0, 0, -Math.PI]} scale={0}>
                              <T.Group name="BigBranch_Leaf_08_02_182" rotation={[0, 0, -Math.PI]} scale={0} />
                            </T.Group>
                            <T.Group name="BigBranch_Leaf_06_184" rotation={[0, 0, -Math.PI]} scale={0} />
                          </T.Group>
                        </T.Group>
                      </T.Group>
                      <T.Group name="BigBranch_Leaf_05_188" rotation={[0, 0, -Math.PI]} scale={0} />
                      <T.Group name="BigBranch_Leaf_04_189" rotation={[0, 0, -Math.PI]} scale={0} />
                    </T.Group>
                    <T.Group name="BigBranch_SmallBranch_02_207" rotation={[0, 0, -Math.PI]} scale={0}>
                      <T.Group name="BigBranch_SmallBranch_03_204" rotation={[0, 0, -Math.PI]} scale={0}>
                        <T.Group name="BigBranch_SmallBranch_04_196" rotation={[0, 0, -Math.PI]} scale={0}>
                          <T.Group name="BigBranch_Flower_02_195" rotation={[0, 0, -Math.PI]} scale={0}>
                            <T.Group name="BigBranch_Flower_02_01_191" rotation={[0, 0, -Math.PI]} scale={0} />
                            <T.Group name="BigBranch_Flower_02_03_192" rotation={[0, 0, -Math.PI]} scale={0} />
                            <T.Group name="BigBranch_Flower_02_04_193" rotation={[0, 0, -Math.PI]} scale={0} />
                            <T.Group name="BigBranch_Flower_02_02_194" rotation={[0, 0, -Math.PI]} scale={0} />
                          </T.Group>
                        </T.Group>
                        <T.Group name="BigBranch_SmallBranch_05_203" rotation={[0, 0, -Math.PI]} scale={0}>
                          <T.Group name="BigBranch_SmallBranch_06_202" rotation={[0, 0, -Math.PI]} scale={0}>
                            <T.Group name="BigBranch_Flower_03_201" rotation={[0, 0, -Math.PI]} scale={0}>
                              <T.Group name="BigBranch_Flower_03_01_197" rotation={[0, 0, -Math.PI]} scale={0} />
                              <T.Group name="BigBranch_Flower_03_02_198" rotation={[0, 0, -Math.PI]} scale={0} />
                              <T.Group name="BigBranch_Flower_03_03_199" rotation={[0, 0, -Math.PI]} scale={0} />
                              <T.Group name="BigBranch_Flower_03_04_200" rotation={[0, 0, -Math.PI]} scale={0} />
                            </T.Group>
                          </T.Group>
                        </T.Group>
                      </T.Group>
                      <T.Group name="BigBranch_Flower_01_206" rotation={[0, 0, -Math.PI]} scale={0}>
                        <T.Group name="BigBranch_Flower_01_01_205" rotation={[0, 0, -Math.PI]} scale={0} />
                      </T.Group>
                    </T.Group>
                  </T.Group>
                  <T.Group name="BigBranch_SmallBranch_01_209" rotation={[0, 0, -Math.PI]} scale={0} />
                </T.Group>
                <T.Group name="BigBranch_Leaf_01_211" rotation={[0, 0, -Math.PI]} scale={0} />
                <T.Group name="BigBranch_Leaf_03_212" rotation={[0, 0, -Math.PI]} scale={0} />
                <T.Group name="BigBranch_Leaf_02_213" rotation={[0, 0, -Math.PI]} scale={0} />
              </T.Group>
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
